db:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: simulator
    MYSQL_ROOT_PASSWORD: admin
simulator-web:
  image: neogrid/simulator-web
  links:
    - db
  ports:
    - "8080:8080"
  environment:
    SIMULATOR_DB_DRIVER: com.mysql.jdbc.Driver
    SIMULATOR_DB_URL: jdbc:mysql://db:3306/simulator
    SIMULATOR_DB_USERNAME: root
    SIMULATOR_DB_PASSWORD: admin
